### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Haris131** [x404xx/Tik-Down#1]
Why TypeError?
![Screenshot_2024-01-06-00-06-43-305_com termux-edit](https://github.com/x404xx/Tik-Down/assets/41672454/a3bd60e0-fed1-4ceb-b45e-de77ea3c5546)

I use Termux app

**Comment by x404xx** [comment]
> Why TypeError? ![Screenshot_2024-01-06-00-06-43-305_com termux-edit](https://private-user-images.githubusercontent.com/41672454/294533269-a3bd60e0-fed1-4ceb-b45e-de77ea3c5546.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MTg2MTgsIm5iZiI6MTcwODgxODMxOCwicGF0aCI6Ii80MTY3MjQ1NC8yOTQ1MzMyNjktYTNiZDYwZTAtZmVkMS00Y2ViLWI0NWUtZGU3N2VhM2M1NTQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDIzNDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2Y2VlZTYzYWUxY2Y2Y2YyYjgyM2JlYTlmZmFhZjk4MzMzM2NhMDkxYTQ1NWE1NDQ4ZmEyODVmY2VjZTEzOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yb6LEpdk08Q4BAzWhIuh2Ajam5jRMbJVgOeE9AJzZUY)
> 
> I use Termux app

Maybe your TikTok video URL is not valid or the video is not available on TikTok.
