### ISSUE TITLE
Can you do one more with snapinsta.app?

### ISSUE THREAD

**Issue by Sinanqd10** [x404xx/Tik-Down#2]
Hello @x404xx 
First of all, Thanks you for sharing.

I would like to know what is your tricks (Tools to monitor) to extract data from (https://snapinsta.app/) . I've tried using the method you used on Tiktok but it doesn't work on Insta. Any suggestion will be appreciated.

**Comment by x404xx** [comment]
> Hello @x404xx First of all, Thanks you for sharing.
> 
> I would like to know what is your tricks (Tools to monitor) to extract data from (https://snapinsta.app/) . I've tried using the method you used on Tiktok but it doesn't work on Insta. Any suggestion will be appreciated.

Yes [here](https://github.com/x404xx/Insta-Down). You're welcome.

**Comment by Sinanqd10** [comment]
Hello @x404xx 

Thanks you very much. this line of header 'Referer': 'https://snapinsta.app/' do the trick :)

**Comment by x404xx** [comment]
> Hello @x404xx 
> 
> 
> 
> Thanks you very much. this line of header 'Referer': 'https://snapinsta.app/' do the trick :) 

You're welcome. Instead, you can try this (https://snapsave.app); it supports videos from Facebook, TikTok, and Instagram. However, you need to implement some code. 😃
